# Generated by Django 4.0.3 on 2022-04-19 00:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerrajero',
            name='tarjeta_presentacion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futbolista',
            name='tarjeta_presentacion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tarjeta_presentacion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
